"""
models/output.py
FinalOutput and its sub-models — the top-level schema returned by the
orchestrator after all agents complete.

Design notes:
- `final_decision` is a flat summary for fast machine-parsing (the "headline").
- `agent_trace` is the full audit log; every agent's AgentResult is appended
  in execution order by the orchestrator.
- `hospital_admission_report` is produced by the Admission Formalities Agent;
  it contains pre-filled form fields derived from the incident data.
- `human_readable_brief` is a short paragraph generated by one LLM call in
  the Admission Formalities Agent — intended for a human reviewer to read at a glance.
- `requires_human_review` is true if ANY agent returned confidence < 0.5 OR
  the Verifier↔Triage loop did not resolve within the cap.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field

from .agent_result import AgentResult


class AssignedAmbulance(BaseModel):
    """Slim summary of the ambulance assigned to this incident."""

    ambulance_id: str = Field(description="ID of the dispatched ambulance.")
    type: str = Field(description="Ambulance type: BLS, ALS, trauma, or neonatal.")
    eta_minutes: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Estimated minutes until ambulance arrives at scene. None if not computable.",
    )


class AssignedHospital(BaseModel):
    """Slim summary of the hospital matched to this incident."""

    hospital_id: str = Field(description="ID of the matched hospital.")
    name: str = Field(description="Human-readable hospital name.")
    distance_km: Optional[float] = Field(
        default=None,
        ge=0.0,
        description="Straight-line distance from incident to hospital in km. None if not computable.",
    )


class FinalDecision(BaseModel):
    """
    Machine-readable headline of the orchestrator's combined decision.
    Designed for fast downstream consumption (e.g. a dispatcher's UI card).
    """

    severity_score: int = Field(
        ge=1,
        le=10,
        description="Final agreed severity score (1 = minor, 10 = immediately life-threatening).",
    )
    ambulance: AssignedAmbulance = Field(description="Ambulance dispatched to this incident.")
    hospital: AssignedHospital = Field(description="Hospital the patient will be taken to.")
    requires_human_review: bool = Field(
        description=(
            "True if any agent confidence < 0.5, or the Verifier↔Triage loop "
            "did not resolve within the cap. A human must review before acting."
        )
    )


class HospitalAdmissionReport(BaseModel):
    """
    Pre-filled admission document generated by the Admission Formalities Agent.
    Fields mirror a realistic intake form so a real hospital system can ingest it.
    """

    patient_name: Optional[str] = Field(
        default=None,
        description="Patient name if known from caller meta (may be None for anonymous incidents).",
    )
    caller_phone: Optional[str] = Field(
        default=None,
        description="Callback number for follow-up.",
    )
    incident_summary: str = Field(
        description="One-sentence structured summary of the emergency (generated, not caller-supplied).",
    )
    presenting_complaint: str = Field(
        description="Clinical description of the primary complaint derived from the incident.",
    )
    suspected_diagnosis: Optional[str] = Field(
        default=None,
        description="Preliminary suspected diagnosis (low-confidence; for reference only).",
    )
    severity_score: int = Field(
        ge=1,
        le=10,
        description="Severity score echoed from FinalDecision for the admissions desk.",
    )
    ambulance_type: str = Field(
        description="Ambulance type dispatched, for hospital preparation.",
    )
    estimated_arrival_minutes: Optional[float] = Field(
        default=None,
        description="ETA in minutes at time of report generation.",
    )
    special_preparations: list[str] = Field(
        default_factory=list,
        description=(
            "List of preparations the hospital should make before arrival, "
            "e.g. ['Activate trauma team', 'Reserve OR suite 2']."
        ),
    )
    report_generated_at: datetime = Field(
        description="UTC timestamp when this report was generated.",
    )


class MapLocation(BaseModel):
    lat: float
    lng: float

class MapAmbulance(BaseModel):
    id: str
    current_location: MapLocation
    eta_to_incident_minutes: Optional[float]

class MapHospital(BaseModel):
    id: str
    location: MapLocation
    distance_from_incident_km: Optional[float]
    eta_incident_to_hospital_minutes: Optional[float]

class MapData(BaseModel):
    incident_location: MapLocation
    ambulance: MapAmbulance
    hospital: MapHospital


class FinalOutput(BaseModel):
    """
    Root output schema of the orchestrator — returned by POST /incident.

    Contains the full audit trail (`agent_trace`) and all decision artefacts.
    """

    incident_id: str = Field(description="Echoes the incident_id from IncidentInput.")
    final_decision: FinalDecision = Field(
        description="Headline decision: severity, ambulance, hospital, review flag."
    )
    agent_trace: list[AgentResult[Any]] = Field(
        default_factory=list,
        description=(
            "Ordered list of every AgentResult produced during this incident's pipeline run. "
            "Append-only; orchestrator adds each result immediately after the agent returns."
        ),
    )
    hospital_admission_report: HospitalAdmissionReport = Field(
        description="Pre-filled admission document for the matched hospital.",
    )
    human_readable_brief: str = Field(
        description=(
            "Short paragraph (3–5 sentences) written by the Admission Formalities Agent "
            "summarising the incident, decision, and any caveats — for a human reviewer."
        ),
    )
    map_data: Optional[MapData] = Field(
        default=None,
        description="Geospatial details for mapping the incident, ambulance, and hospital.",
    )
